# Generated by Django 5.2.1 on 2025-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandName',
            field=models.CharField(default='Unknown Brand', max_length=255),
            preserve_default=False,
        ),
    ]
