# Generated by Django 5.2.1 on 2025-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brandname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandName',
            field=models.CharField(default='Unknown Brand', max_length=255),
        ),
    ]
