# Generated by Django 5.2.1 on 2025-09-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_brandname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_picture',
            new_name='main_image',
        ),
    ]
