# Generated by Django 5.2.1 on 2025-11-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_total_amount_order_downpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
