# Generated by Django 5.2.1 on 2025-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message_to_seller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
