# Generated by Django 5.2.1 on 2025-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_message_to_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partial_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
