# Generated by Django 5.2.1 on 2025-10-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_useractivity_options_and_more'),
        ('users', '0009_artisan_artisanphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artisan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.artisan'),
            preserve_default=False,
        ),
    ]
