# Generated by Django 5.2.1 on 2025-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
