# Generated by Django 5.2.1 on 2025-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_long_description_ordertimeline_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='payment_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
