# Generated by Django 5.2.1 on 2025-12-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_paymentproof_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertimeline',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
