# Generated by Django 5.2.1 on 2025-12-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_ordertimeline_reason'),
        ('users', '0012_shippingaddress_landmark_shippingaddress_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.artisan'),
        ),
    ]
