# Generated by Django 5.2.1 on 2025-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_order_gcash_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partial_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
