# Generated by Django 5.2.1 on 2025-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_order_partial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gcash_proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
