# Generated by Django 5.2.1 on 2025-12-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_order_gcash_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('awaiting_verification', 'Awaiting Verification'), ('processing', 'Processing'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('to_review', 'To Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund', 'Refund')], default='awaiting_payment', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='payment_type',
            field=models.CharField(choices=[('downpayment', 'Downpayment'), ('fullpayment', 'Full Payment'), ('cod_balance', 'COD Balance')], default='shipping fee', max_length=20),
        ),
    ]
