# Generated by Django 5.2.1 on 2025-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_refund_ordertimeline_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
