# Generated by Django 5.2.1 on 2025-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_orderitem_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
