# Generated by Django 5.2.1 on 2025-12-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='🔔', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('payment', 'Payment Update'), ('shipping', 'Shipping Update'), ('message', 'Message'), ('system', 'System'), ('inventory', 'Inventory Alert'), ('artisan', 'Artisan Update')], default='system', max_length=50),
        ),
    ]
