# Generated by Django 5.2.1 on 2025-11-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_artisan_pickup_address_artisan_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='gcash_qr',
            field=models.ImageField(blank=True, help_text='Upload the GCash QR code for preorder downpayment', null=True, upload_to='artisan_qr_codes/'),
        ),
    ]
