# Generated by Django 5.2.1 on 2025-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_artisan_gcash_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
