# Generated by Django 5.2.1 on 2025-12-17 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_shippingaddress_landmark_shippingaddress_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.artisan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_artisans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'artisan')},
            },
        ),
    ]
